"""initial migration

Revision ID: f7b5451c46f3
Revises: 00ae1378de91
Create Date: 2024-10-16 20:01:14.931727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import models

# revision identifiers, used by Alembic.
revision: str = 'f7b5451c46f3'
down_revision: Union[str, None] = '00ae1378de91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
